### ISSUE TITLE
nonzero exit code on failures

### ISSUE THREAD

**Issue by flokli** [wipbar/fossbeamer#2]
We should detect when we unwrap, so the compositor has a chance to restart the application on crashes.

**Comment by VanuPhantom** [comment]
@freyacodes just hypothesised that [*`systemd`*](https://systemd.io/) should restart the application when it exits. I'll asign them to this issue, they'll report back here with their investigation's conclusion.

**Comment by freyacodes** [comment]
Something like this perhaps
```nix
systemd.services."cage-tty1".serviceConfig = {
  RestartSec = 5;
  Restart = "always";
};
```

I looked at cage briefly, and it doesn't look like it manages restarting its children.

**Comment by flokli** [comment]
This issue is about the zero exit code of the rust binary I was getting, even when it failed due to missing config. It caused systemd to report success.

**Comment by flokli** [comment]
I couldn't repro this anymore - saw nonzero exit codes on errors. I'll do some research on cage behaviour with it's only payload being terminated, and ensuring restarts, probably using the snippet above.
