### ISSUE TITLE
create config.json file if it doesn't exist on startup

### ISSUE THREAD

**Issue by flokli** [wipbar/fossbeamer#3]
We should have the application create `config.json` on startup, if it's not present.

We should still fail if there is a config, and it's invalid, not overwrite it with defaults in that case.

**Comment by freyacodes** [comment]
I think we should just link `config.json` to a path on the nix store, linked via `systemd.tmpfiles` in `configuration.nix`. The config files will not be unique.

**Comment by flokli** [comment]
That'll still make it part of the nix configuration, and drag it to this state on every reboot. Which contents would you like to have?

**Comment by freyacodes** [comment]
> That'll still make it part of the nix configuration

As with all other parts of configuration, except that which is directly controlled via MQTT

> and drag it to this state on every reboot

I'm not sure I understand the problem. The file would be static, and linking to the store on reboot should be no issue. 

> Which contents would you like to have?

As I understand it, it would just need the host and port of the MQTT server. The `id` field is optional, and we will be relying on CPU serial numbers.

**Comment by flokli** [comment]
This file cannot be controlled via MQTT, as it contains the config to the mqtt broker itself.

If I point it somewhere in the nix store, I need to describe the file contents I point to with Nix, and make that part of the nix configuration.

So what should I point it to?

**Comment by freyacodes** [comment]
>This file cannot be controlled via MQTT, as it contains the config to the mqtt broker itself.

Exactly. All this file currently does is facilitate an MQTT connection.

> So what should I point it to?

`pkgs.writeText <name> <contents>` returns a derivation that we can point to. This would be the same for all the pis.

So we might have something like:

```nix
systemd.tmpfiles.rules = [
  "L /home/kiosk/config.json - - - - ${pkgs.writeText "config.json" actualJsonContents}"
];
```

**Comment by flokli** [comment]
Yes, I understand how to do it. I'm asking which *exact values* you want it to point to, in this repo. Because we want to be able to build a fully working nixos config that does the right thing on bootup.

**Comment by flokli** [comment]
I still think having the rust side of things creating it is nicer, as it allows to ssh in and change the config, and it won't get overwritten (contrary to the tmpfiles approach, which will revert our changes on every reboot/config switch).

**Comment by freyacodes** [comment]
What would you expect the default configuration to be like? It would seem that it would not work out of the box unless we provide an opinionated default host. Are you expecting to manually `scp` a config onto each pi?

**Comment by flokli** [comment]
No, I'd expect to just hardcode mqtt.wip.bar at the default port something, and point the DNS record to something later. Is that ok?

**Comment by freyacodes** [comment]
There is no consensus. People do not seem to like the idea of hardcoding a host in this repository, unless perhaps it is a public broker.

**Comment by VanuPhantom** [comment]
Earlier this evening, as far as I'm aware, consensus was reached on this matter. We've decided to put in place the following system;

When calling *[Fossbeamer](https://github.com/VanuPhantom/fossbeamer)*, an optional parameter called `--default-config` can be provided. This parameter causes the app to load the configuration at the specified location if an override config (a file named `config.json` in the working directory) is not present.

#5 implements these changes and resolves this issue.
